[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bilayers-schema"
version = "0.1.0"
description = "Schema and shared type definitions for Bilayers"
authors = [
    {name = "Rajavi Shah", email = "shahraja@broadinstitute.org"},
    {name = "Nodar Gogoberidze", email = "gnodar01@gmail.com"},
    {name = "Beth Cimini", email = "bcimini@broadinstitute.org"}
]
maintainers = [
    {name = "Rajavi Shah", email = "shahraja@broadinstitute.org"},
    {name = "Nodar Gogoberidze", email = "gnodar01@gmail.com"},
    {name = "Beth Cimini", email = "bcimini@broadinstitute.org"}
]
readme = "README.md"
license = "BSD-3-Clause"
requires-python = ">=3.9"
dependencies = [
    "pyyaml>=6.0.1,<7",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["bilayers_schema*"]

[tool.setuptools.package-data]
bilayers_schema = ["schema.yaml", "py.typed"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tool.pixi.dependencies]
python = ">=3.9"

[tool.pixi.pypi-dependencies]
bilayers-schema = { path = ".", editable = true }

[project.optional-dependencies]
lint = ["ruff"]
typecheck = ["pyright", "types-pyyaml"]
test = ["pytest", "linkml-runtime"]
dev = [
    "bilayers-schema[lint]",
    "bilayers-schema[typecheck]",
    "bilayers-schema[test]"
]


[tool.pixi.feature.dev.pypi-dependencies]
pre-commit = "*"

[tool.pixi.feature.dev.activation]
scripts = ["scripts/install-pre-commit.sh"]

[tool.pixi.environments]
dev = ["dev", "lint", "typecheck"]

[tool.ruff]
line-length = 160
preview = true

[tool.ruff.lint]
select = ["W", "F", "C", "E"]

[tool.pyright]
pythonVersion = "3.10"
