name: Notify bilayers-algorithms of schema change

on:
    pull_request:
        branches:
            - main
        types:
            - closed

# Since the job below never uses GITHUB_TOKEN (repository-dispatch auth comes from REPO_TRIGGER_TOKEN)
# we've removed the default permission. In future, if we add a step that uses GITHUB_TOKEN, we should explicitly add the required permissions to that step.
permissions: {}

jobs:
    notify:
        name: Notify bilayers-algorithms of schema change
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true
        steps:
            - name: Notify bilayers-algorithms of schema change
              uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 #v4.0.1
              with:
                  token: ${{ secrets.REPO_TRIGGER_TOKEN }}
                  repository: bilayer-containers/bilayers-algorithms
                  event-type: schema-updated
                  client-payload: '{"pr_number": "${{ github.event.pull_request.number }}", "schema_commit_sha": "${{ github.event.pull_request.merge_commit_sha }}"}'